# Generated by Django 4.1 on 2022-09-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oraganization_Model',
            fields=[
                ('Organization_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Organization_Name', models.CharField(max_length=30)),
                ('Organization_Location', models.CharField(max_length=30)),
                ('Organization_Address', models.JSONField()),
                ('Organization_No_Of_Employee', models.IntegerField()),
                ('Organization_Turnover', models.BigIntegerField()),
                ('Organization_Capitalamount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Model',
            fields=[
                ('Employee_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Employee_Name', models.CharField(max_length=20)),
                ('Employee_Salary', models.BigIntegerField()),
                ('Employee_Address', models.JSONField()),
                ('Employee_Designation', models.CharField(max_length=30)),
                ('Employee_Org_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.oraganization_model')),
            ],
        ),
    ]
