# Generated by Django 4.1 on 2022-09-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_employee_model_is_delete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_model',
            old_name='Employee_Org_Id',
            new_name='Organization_Id',
        ),
    ]
