# Generated by Django 4.1 on 2022-09-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_rename_employee_org_id_employee_model_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_model',
            name='Employee_Salary',
            field=models.FloatField(),
        ),
    ]
